language: generic

os: linux

branches:
        only:
                - master

notifications:
        email:
                on_success: never
                on_failure: never

before_install:
        # - openssl aes-256-cbc -k "$KEYFILE_PASS" -in "${UPLOAD_KEYPATH}.enc" -out "${UPLOAD_KEYPATH}" -d

# run the script to download and install Unity editor
install:
        - sudo -E sh ./Travis-Scripts/install.sh

# run the script for unit tests and builds
script:
        - sudo -E sh ./Travis-Scripts/build.sh

# run the script to upload the builds as tarballs
after_success:
        - sudo -E sh ./Travis-Scripts/post_build.sh
